# Generated by Django 5.0.3 on 2024-03-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_category_title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game category',
                'verbose_name_plural': 'Game categories',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(help_text='Here add name of product', max_length=50)),
                ('game_price', models.FloatField()),
                ('game_count', models.IntegerField()),
                ('game_descriptions', models.TextField()),
                ('game_image', models.FileField(upload_to='product_images')),
                ('game_created_at', models.DateTimeField(auto_now_add=True)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_products.gamecategorymodel')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
